name: stitten_business
description: "A local-first Flutter shop management ERP and financial summary tool."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # قاعدة البيانات المحلية السريعة
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # أدوات التحليل البرمجي
  flutter_lints: ^5.0.0
  
  # أدوات توليد الكود المرتبطة بـ Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # يمكنك إضافة الأيقونات أو الخطوط هنا لاحقاً إذا احتجت لذلك
  # assets:
  #   - assets/
  
