name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # تحديث إلى v4
      - name: Checkout code
        uses: actions/checkout@v4

      # تحديث إلى v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Flutter Android project files
        run: flutter create --project-name sttiten_bisness . --org com.stitten.stores --platforms=android

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # تحديث إلى v4 لحل الخطأ
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
